import { DataItem } from '.';
export default <DataItem[]>[
  {
    name: 'getSchemeName',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/getSchemeName',
      method: 'GET',
    },
    target: 'getSchemeNameDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'getDetails',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/earlyWarnCases/getDetails',
      method: 'POST',
    },
    target: 'getDetailsDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'getOptionsByType',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/earlyWarnCases/getOptionsByType',
      method: 'POST',
    },
    target: 'getOptionsByTypeDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'getPublicSentimentDictionary',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/earlyWarnCases/getPublicSentimentDictionary',
      method: 'POST',
    },
    target: 'getPublicSentimentDictionaryDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'getPageList',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/earlyWarnCases/getPageList',
      method: 'POST',
    },
    target: 'getPageListDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'deleteEarlyWarnCase',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/earlyWarnCases/deleteEarlyWarnCase',
      method: 'POST',
    },
    target: 'deleteEarlyWarnCaseDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'addEarlyWarnCase',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/earlyWarnCases/addEarlyWarnCase',
      method: 'POST',
    },
    target: 'addEarlyWarnCaseDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'updateEarlyWarnCase',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/earlyWarnCases/updateEarlyWarnCase',
      method: 'POST',
    },
    target: 'updateEarlyWarnCaseDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'getEmailList',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/sendDimension/list',
      method: 'GET',
    },
    target: 'getEmailListDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'statelist',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/state/list',
      method: 'GET',
    },
    target: 'statelistDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'creditPressurelist',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/creditPressure/list',
      method: 'GET',
    },
    target: 'creditPressurelistDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'warningPool',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/warningPool',
      method: 'GET',
    },
    target: 'warningPoolDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'warningScheme',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/warningScheme',
      method: 'GET',
    },
    target: 'warningSchemeDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'alertEmailPage',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/page',
      method: 'GET',
    },
    target: 'alertEmailPageDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'alertEmail',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail',
      method: 'POST',
    },
    target: 'alertEmailDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'recipient',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/recipient/email',
      method: 'GET',
    },
    target: 'recipientDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'itemSimples',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/bizdict/item/simple',
      method: 'GET',
    },
    target: 'itemSimplesDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'alertEmailState',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/state',
      method: 'PUT',
    },
    target: 'alertEmailStateDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'emailPageList',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/email/page',
      method: 'GET',
    },
    target: 'emailPageListDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
  {
    name: 'alertEmailFile',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/file',
      method: 'GET',
    },
    target: 'alertEmailFileDataImpl',
    path: 'EarlyWarningProgramData/EarlyWarningProgramDataImpl',
  },
];
