import { DataItem } from '.';
export default <DataItem[]>[
  {
    name: 'getSearchMessage',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/getSearchMessage',
      method: 'POST',
    },
    target: 'getSearchMessageDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'search',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/search',
      method: 'POST',
    },
    target: 'searchDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'searchTab',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/searchTab',
      method: 'POST',
    },
    target: 'searchTabDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'excel',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/export/excel',
      method: 'POST',
    },
    target: 'excelDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'rightExcel',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/export/rightExcel',
      method: 'POST',
    },
    target: 'rightExcelDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getOpinionsInfo',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/subject/detail/getOpinionsInfo',
      method: 'POST',
    },
    target: 'getOpinionsInfoDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getPriceInfo',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/subject/detail/getPriceInfo',
      method: 'POST',
    },
    target: 'getPriceInfoDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getFinanceInfo',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/subject/detail/getFinanceInfo',
      method: 'POST',
    },
    target: 'getFinanceInfoDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getPositionInfo',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/subject/detail/getPositionInfo',
      method: 'POST',
    },
    target: 'getPositionInfoDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getSubjectDetailInfo',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/search/getSubjectDetailInfo',
      method: 'POST',
    },
    target: 'getSubjectDetailInfoDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'distribution',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/detail/creditstress/distribution',
      method: 'POST',
    },
    target: 'distributionDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getEarlyWarnPools',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/getEarlyWarnPools',
      method: 'GET',
    },
    target: 'getEarlyWarnPoolsDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getEarlyWarnPlans',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/getEarlyWarnPlans',
      method: 'GET',
    },
    target: 'getEarlyWarnPlansDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getMainNames',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/getMainNames',
      method: 'POST',
    },
    target: 'getMainNamesDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'bizdictPosition',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/bizdict/item/simple/position',
      method: 'GET',
    },
    target: 'bizdictPositionDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'bizdictDefault',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/bizdict/item/simple/default',
      method: 'GET',
    },
    target: 'bizdictDefaultDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'getPositionDetailInfo',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/search/getPositionDetailInfo',
      method: 'POST',
    },
    target: 'getPositionDetailInfoDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'oneDayCreditPressure',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/bizdict/item/simple/oneDayCreditPressure',
      method: 'GET',
    },
    target: 'oneDayCreditPressureDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'fiveDayCreditPressure',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/bizdict/item/simple/fiveDayCreditPressure',
      method: 'GET',
    },
    target: 'fiveDayCreditPressureDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'thirtyDayCreditPressure',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/bizdict/item/simple/thirtyDayCreditPressure',
      method: 'GET',
    },
    target: 'thirtyDayCreditPressureDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'exportPositions',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/EarlyWarnDetailsController/export/positions',
      method: 'POST',
    },
    target: 'exportPositionsDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
  {
    name: 'zhmcList',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/alertEmail/zhmc/list',
      method: 'GET',
    },
    target: 'zhmcListDataImpl',
    path: 'EarlyWarningDetailsData/EarlyWarningDetailsDataImpl',
  },
];
