import { DataItem } from '.';
export default <DataItem[]>[
  {
    name: 'getDictionary',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/getDictionary',
      method: 'POST',
    },
    target: 'getDictionaryDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'getPrimaryList',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/getPrimaryList',
      method: 'POST',
    },
    target: 'getPrimaryListDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'doFocus',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/doFocus',
      method: 'POST',
    },
    target: 'doFocusDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'alertPoolRemove',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/alertPoolRemove',
      method: 'POST',
    },
    target: 'alertPoolRemoveDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'queryAlertPool',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/queryAlertPool',
      method: 'POST',
    },
    target: 'queryAlertPoolDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'addAlertPool',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/addAlertPool',
      method: 'POST',
    },
    target: 'addAlertPoolDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'updateAlertPool',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/updateAlertPool',
      method: 'POST',
    },
    target: 'updateAlertPoolDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'alertPoolCollect',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/alertPoolCollect',
      method: 'POST',
    },
    target: 'alertPoolCollectDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'deleteAlertPool',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/deleteAlertPool',
      method: 'POST',
    },
    target: 'deleteAlertPoolDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'getDetailList',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/getDetailList',
      method: 'POST',
    },
    target: 'getDetailListDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'setAlertPoolExcel',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/export/excel',
      method: 'POST',
    },
    target: 'setAlertPoolExcelDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'earlywarnpoolTemplate',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/download/earlywarnpoolTemplate',
      method: 'POST',
    },
    target: 'earlywarnpoolTemplateDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'earlywarnpoolInfo',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/import/earlywarnpoolInfo',
      method: 'POST',
    },
    target: 'earlywarnpoolInfoDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'saveBatchByUpload',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/saveBatchByUpload',
      method: 'POST',
    },
    target: 'saveBatchByUploadDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'validAlertPoolName',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/validAlertPoolName',
      method: 'POST',
    },
    target: 'validAlertPoolNameDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'getConditions',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/getConditions',
      method: 'POST',
    },
    target: 'getConditionsDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'getCompositeTreeConditions',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/getCompositeTreeConditions',
      method: 'POST',
    },
    target: 'getCompositeTreeConditionsDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'getAlertPoolDetail',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/getAlertPoolDetail',
      method: 'POST',
    },
    target: 'getAlertPoolDetailDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'updateAlertPoolCondition',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/updateAlertPoolCondition',
      method: 'POST',
    },
    target: 'updateAlertPoolConditionDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
  {
    name: 'getAlertPoolDisplayCondition',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'bondWarning',
    value: {
      url: '/setAlertPool/getAlertPoolDisplayCondition',
      method: 'POST',
    },
    target: 'getAlertPoolDisplayConditionDataImpl',
    path: 'SetAlertPoolData/SetAlertPoolDataImpl',
  },
];
