import { DataItem } from '.';
export default <DataItem[]>[
  {
    name: 'getPage',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/getPage',
      method: 'POST',
    },
    target: 'getPageDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: 'getAllCompositeTree',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/getAllCompositeTree',
      method: 'POST',
    },
    target: 'getAllCompositeTreeDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: 'getCompositeTreeByTreeId',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/getCompositeTreeByTreeId',
      method: 'GET',
    },
    target: 'getCompositeTreeByTreeIdDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: 'getCompositeTreeByTreeIdHasAudit',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/getCompositeTreeByTreeIdHasAudit',
      method: 'GET',
    },
    target: 'getCompositeTreeByTreeIdHasAuditDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: "getCompositeTreeByUserAndTreeId",
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/getCompositeTreeByUserAndTreeId',
      method: 'GET',
    },
    target: 'getCompositeTreeByUserAndTreeIdDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: "makeCompositeTree",
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/makeCompositeTree',
      method: 'POST',
    },
    target: 'makeCompositeTreeDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: "saveCompositeTree",
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/saveCompositeTree',
      method: 'POST',
    },
    target: 'saveCompositeTreeDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: "userAuth",
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/userAuth',
      method: 'POST',
    },
    target: 'userAuthDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: "authAudit",
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/authAudit',
      method: 'POST',
    },
    target: 'authAuditDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  }, 
  {
    name: "removeCompositeTree",
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/removeCompositeTree',
      method: 'GET',
    },
    target: 'removeCompositeTreeDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  }, 
  {
    name: 'authAllAudit',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/authAllAudit',
      method: 'POST',
    },
    target: 'authAllAuditDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  }, 
  {
    name: 'getWaitAuditCount',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/getWaitAuditCount',
      method: 'GET',
    },
    target: 'getWaitAuditCountDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: 'getCompositeTreeDefine',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/getCompositeTreeDefine',
      method: 'GET',
    },
    target: 'getCompositeTreeDefineDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
  {
    name: 'getAuthCompositeTree',
    type: 'data',
    useBaseURL: true,
    gatewayType: 'baseFunction',
    value: {
      url: '/userAuth/getAuthCompositeTree',
      method: 'POST',
    },
    target: 'getAuthCompositeTreeDataImpl',
    path: 'UserAuthData/UserAuthDataImpl',
  },
];
